{ config, pkgs, ... }:

{
  programs.git = {
    enable = true;

    userName = "awollgarten";
    userEmail = "alexander.wollgarten@aimpower.ai";
    ignores = [
      # Some files which might be generated by system or tools
      "*~"
      "*.swp"
      "*.swn"
      "*.swo"
      "*.orig"
      "*.rej"
      "*.pyc"
      "*.bak"
      "*/tags"
      "/tags"
      "*.~lock.*#"
      ".phpactor.json"
      ".ignore"
      # As I'm using nix-shell in many projects for my own confidence
      "shell.nix"

      # Some generics which occur in some projects
      "build/"
      "logs/"
    ];

    extraConfig = {
      init = { defaultBranch = "main"; };

      push = { default = "current"; };

      pull = { rebase = true; };

      rebase = { autoStash = true; };

      merge = { ff = true; };
    };

  };
}
